branches:
  
before_script:
- git config --global user.name 'elmas3 via Travis CI'
- git config --global user.email 'elmas3@users.noreply.github.com '

script:
- export GIT_COMMITTER_NAME=elmas3-via-TravisCI
- export GIT_COMMITTER_EMAIL=elmas3@users.noreply.github.com 

- git checkout master || exit
- git merge "$TRAVIS_PULL_REQUEST_BRANCH" || exit
- '[ "$TRAVIS_BRANCH" == "master" ]'
- '[ $GH_TOKEN ]'
- 'git push --force https://$GH_TOKEN@github.com/elmas3/pull-request-practice.git HEAD:gh-pages'

env:
  global:
  - GIT_COMMITTER_NAME=elmas3-via-TravisCI
  - GIT_COMMITTER_EMAIL=elmas3@users.noreply.github.com 
  - GIT_AUTHOR_NAME=elmas3-via-TravisCI
  - GIT_AUTHOR_EMAIL=elmas3@users.noreply.github.com 
